# Generated by Django 5.1.2 on 2025-06-16 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='web.personal')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('P', 'En reparación')], default='B', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.categoriaherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes_Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='1999-01-01')),
                ('hora', models.TimeField(default='00:00')),
                ('descripcion', models.CharField()),
                ('persona_responsable', models.CharField()),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanica.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades_Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField()),
                ('serial_carroceria', models.CharField()),
                ('serial_chasis', models.CharField()),
                ('marca', models.CharField()),
                ('año', models.CharField()),
                ('modelo', models.CharField()),
                ('placas', models.CharField()),
                ('tipo_filtro_aceite', models.CharField()),
                ('tipo_filtro_combustible', models.CharField()),
                ('bateria', models.CharField()),
                ('numero_tag', models.CharField()),
                ('tipo_bujia', models.CharField()),
                ('uso', models.CharField()),
                ('capacidad_carga', models.CharField()),
                ('numero_ejes', models.CharField()),
                ('numero_puestos', models.CharField()),
                ('tipo_combustible', models.CharField()),
                ('tipo_aceite', models.CharField()),
                ('medida_neumaticos', models.CharField()),
                ('tipo_correa', models.CharField()),
                ('estado', models.CharField()),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('centro_medico', models.CharField(max_length=200)),
                ('medico', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_medicos', to='mecanica.conductor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conductor',), name='unique_certificado_por_conductor')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanica.herramienta')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de herramientas',
                'unique_together': {('herramienta', 'unidad', 'fecha_devolucion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('P', 'En reparación')], max_length=1)),
                ('observaciones', models.TextField(blank=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.herramienta')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanica.inventariounidad')),
            ],
            options={
                'unique_together': {('inventario', 'herramienta')},
            },
        ),
        migrations.CreateModel(
            name='LicenciaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('2', '2° Segundo Grado'), ('3', '3° Tercer Grado'), ('4', '4° Cuarto Grado'), ('5', '5° Quinto Grado')], max_length=1)),
                ('numero_licencia', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('organismo_emisor', models.CharField(max_length=100)),
                ('restricciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='mecanica.conductor')),
            ],
            options={
                'verbose_name': 'Licencia de Conductor',
                'verbose_name_plural': 'Licencias de Conductores',
                'constraints': [models.UniqueConstraint(fields=('numero_licencia', 'tipo_licencia'), name='unique_licencia_numero_tipo')],
            },
        ),
    ]
