# Generated by Django 5.1.2 on 2025-06-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0001_initial'),
        ('web', '0078_remove_herramienta_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleinventario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='detalleinventario',
            name='herramienta',
        ),
        migrations.RemoveField(
            model_name='detalleinventario',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='inventariounidad',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='inventariounidad',
            name='unidad',
        ),
        migrations.AlterModelOptions(
            name='asignacionherramienta',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name_plural': 'Asignaciones de herramientas'},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionherramienta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignacionherramienta',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mecanica.herramienta'),
        ),
        migrations.AlterField(
            model_name='asignacionherramienta',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_responsable', to='web.personal'),
        ),
        migrations.AlterField(
            model_name='asignacionherramienta',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_herramientas', to='web.unidades'),
        ),
        migrations.AddConstraint(
            model_name='asignacionherramienta',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_devolucion__isnull', True)), fields=('herramienta', 'unidad'), name='unique_active_assignment'),
        ),
        migrations.DeleteModel(
            name='DetalleInventario',
        ),
        migrations.DeleteModel(
            name='InventarioUnidad',
        ),
    ]
