# Generated by Django 5.1.2 on 2025-06-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0002_alter_detalleinventario_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionherramienta',
            name='responsable',
        ),
    ]
