# Generated by Django 5.1.2 on 2025-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0003_remove_asignacionherramienta_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramienta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
