# Generated by Django 5.1.2 on 2025-07-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0004_asignacionherramienta_cantidad'),
        ('web', '0090_remove_movimientobien_bien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades_detalles',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_unidad', to='web.unidades'),
        ),
    ]
