# Generated by Django 5.1.2 on 2025-08-28 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0005_alter_unidades_detalles_id_unidad'),
        ('web', '0097_institucion_titulos_academicos_carrera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('recibido_por', models.CharField(max_length=100)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanica.asignacionherramienta')),
            ],
            options={
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='ReasignacionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_reasignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=100)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanica.herramienta')),
                ('unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_entrada', to='web.unidades')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_salida', to='web.unidades')),
            ],
            options={
                'ordering': ['-fecha_reasignacion'],
            },
        ),
    ]
