# Generated by Django 5.1.2 on 2025-08-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0006_devolucionherramienta_reasignacionherramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasignacionherramienta',
            name='tipo_operacion',
            field=models.CharField(choices=[('nueva', 'Nueva Asignación'), ('suma', 'Suma a Existente')], default='nueva', max_length=10),
        ),
    ]
