# Generated by Django 5.1.2 on 2025-08-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0007_reasignacionherramienta_tipo_operacion'),
        ('web', '0097_institucion_titulos_academicos_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasignacionherramienta',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
    ]
