# Generated by Django 5.1.2 on 2025-08-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0008_alter_reasignacionherramienta_responsable'),
        ('web', '0097_institucion_titulos_academicos_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionherramienta',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
    ]
