# Generated by Django 5.1.2 on 2025-08-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del insumo (ej: Cloruro de Sodio)', max_length=200)),
                ('presentacion', models.CharField(help_text='Formato en que viene el insumo (ej: Caja x20, Frasco de 500ml)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada del insumo.')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del inventario (ej: Principal, Estación 1)', max_length=100, unique=True)),
                ('is_principal', models.BooleanField(default=False, help_text='Marca si este es el inventario principal.')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Material Quirúrgico)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Número de items en el lote.')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de los items en el lote.')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el lote fue registrado.')),
                ('insumo', models.ForeignKey(help_text='El tipo de insumo de este lote.', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='insumos_medicos.insumo')),
                ('inventario', models.ForeignKey(help_text='El inventario donde se encuentra este lote.', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='insumos_medicos.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('ASIGNACION', 'Asignación'), ('DEVOLUCION', 'Devolución')], help_text='Tipo de movimiento (Entrada, Salida, etc.).', max_length=15)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de items que se movieron.')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento.')),
                ('descripcion', models.TextField(blank=True, help_text='Notas o detalles adicionales del movimiento.', null=True)),
                ('inventario_destino', models.ForeignKey(blank=True, help_text='Inventario al que se movió el insumo (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='insumos_medicos.inventario')),
                ('inventario_origen', models.ForeignKey(help_text='Inventario desde donde se movió el insumo.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='insumos_medicos.inventario')),
                ('lote', models.ForeignKey(help_text='Lote al que pertenece este movimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='insumos_medicos.lote')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de insumo al que pertenece.', on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='insumos_medicos.tipoinsumo'),
        ),
    ]
