# Generated by Django 5.1.2 on 2025-08-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='lote',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_vencimiento_lote',
            field=models.DateField(default=None, help_text='Fecha de vencimiento del lote al momento del movimiento.'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='insumo',
            field=models.ForeignKey(default=None, help_text='El insumo que se movió.', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='insumos_medicos.insumo'),
        ),
    ]
