# Generated by Django 5.1.2 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_instagrampost'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='fecha',
            field=models.DateTimeField(default='2000-01-01T00:00:00'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='url',
            field=models.URLField(),
        ),
    ]
