# Generated by Django 5.1.2 on 2024-11-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_instagrampost_fecha_alter_instagrampost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion_preventiva',
            name='apellidos',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retencion_preventiva',
            name='cedula',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retencion_preventiva',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retencion_preventiva',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='retencion_preventiva',
            name='material_utilizado',
            field=models.CharField(max_length=100),
        ),
    ]
