# Generated by Django 5.1.2 on 2024-11-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_retencion_preventiva_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=80)),
                ('apellido_oficial', models.CharField(max_length=80)),
                ('cedula_oficial', models.CharField(max_length=80)),
                ('nro_unidad', models.CharField(max_length=80)),
                ('nro_cuadrante', models.CharField(max_length=80)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_comision')),
            ],
        ),
    ]
