# Generated by Django 5.1.2 on 2024-11-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_tipos_comision_comisiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisiones',
            name='procedimiento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='unidad',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
        ),
    ]
