# Generated by Django 5.1.2 on 2024-12-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_abastecimiento_agua_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeticiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('datos_post', models.JSONField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.usuarios')),
            ],
        ),
    ]
