# Generated by Django 5.1.2 on 2024-12-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_registropeticiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos_Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_capacitacion', models.CharField(max_length=40)),
                ('tipo_clasificacion', models.CharField(max_length=40)),
                ('personas_beneficiadas', models.CharField(max_length=4)),
                ('descripcion', models.TextField()),
                ('material_utilizado', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('id_procedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.procedimientos')),
            ],
        ),
    ]
