# Generated by Django 5.1.2 on 2025-01-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_procedimientos_brigada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion_Preventiva_Incendios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cilindro', models.CharField(max_length=60)),
                ('capacidad', models.CharField(max_length=60)),
                ('serial', models.CharField(max_length=60)),
                ('nro_constancia_retencion', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('material_utilizado', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.incendios')),
            ],
        ),
    ]
