# Generated by Django 5.1.2 on 2025-01-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_retencion_preventiva_incendios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retencion_preventiva_incendios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='retencion_preventiva_incendios',
            name='material_utilizado',
        ),
        migrations.RemoveField(
            model_name='retencion_preventiva_incendios',
            name='status',
        ),
    ]
