# Generated by Django 5.1.2 on 2025-01-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_remove_retencion_preventiva_incendios_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Vehiculo_Derrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField()),
                ('marca', models.CharField()),
                ('color', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=40)),
                ('placas', models.CharField(max_length=40)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mitigacion_riesgos')),
            ],
        ),
    ]
