# Generated by Django 5.1.2 on 2025-01-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_detalles_vehiculo_derrame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('talla_camisa', models.TextField()),
                ('talla_pantalon', models.TextField()),
                ('talla_zapato', models.TextField()),
                ('grupo_sanguineo', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
