# Generated by Django 5.1.2 on 2025-02-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_detalles_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comercio', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('nombre_comercio', models.CharField(max_length=100)),
                ('rif_empresarial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('hora_solicitud', models.TimeField()),
                ('tipo_servicio', models.CharField()),
                ('solicitante_nombre_apellido', models.CharField()),
                ('solicitante_cedula', models.CharField()),
                ('tipo_representante', models.CharField()),
                ('rif_representante_legal', models.CharField()),
                ('direccion', models.CharField()),
                ('estado', models.CharField()),
                ('municipio', models.CharField()),
                ('parroquia', models.CharField()),
                ('numero_telefono', models.CharField()),
                ('correo_electronico', models.CharField()),
                ('pago_tasa', models.CharField()),
                ('referencia', models.CharField()),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.BooleanField()),
                ('cedula_vencimiento', models.DateField()),
                ('rif_representante', models.BooleanField()),
                ('rif_representante_vencimiento', models.DateField()),
                ('rif_comercio', models.BooleanField()),
                ('rif_comercio_vencimiento', models.DateField()),
                ('permiso_anterior', models.BooleanField()),
                ('registro_comercio', models.BooleanField()),
                ('documento_propiedad', models.BooleanField()),
                ('cedula_catastral', models.BooleanField()),
                ('cedula_catastral_vencimiento', models.DateField()),
                ('carta_autorizacion', models.BooleanField()),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.solicitudes')),
            ],
        ),
    ]
