# Generated by Django 5.1.2 on 2025-02-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_comercio_solicitudes_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.municipios'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.parroquias'),
        ),
    ]
