# Generated by Django 5.1.2 on 2025-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_alter_solicitudes_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_catastral_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_comercio_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_representante_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
