# Generated by Django 5.1.2 on 2025-02-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_requisitos_cedula_catastral_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='id_division',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='web.divisiones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='carta_autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_catastral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_catastral_vencimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_identidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_vencimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='documento_propiedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='permiso_anterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='registro_comercio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_comercio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_comercio_vencimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_representante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_representante_vencimiento',
            field=models.DateField(blank=True),
        ),
    ]
