# Generated by Django 5.1.2 on 2025-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_unidades_id_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='id_division',
        ),
        migrations.AddField(
            model_name='unidades',
            name='id_division',
            field=models.ManyToManyField(to='web.divisiones'),
        ),
    ]
