# Generated by Django 5.1.2 on 2025-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_remove_unidades_id_division_unidades_id_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_procedimientos',
            name='id_division',
            field=models.ManyToManyField(to='web.divisiones'),
        ),
    ]
