# Generated by Django 5.1.2 on 2025-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_tipos_procedimientos_id_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_catastral_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='cedula_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_comercio_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitos',
            name='rif_representante_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
