# Generated by Django 5.1.2 on 2025-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_alter_requisitos_cedula_catastral_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitos',
            name='plano_bomberil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='metodo_pago',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
