# Generated by Django 5.1.2 on 2025-02-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_requisitos_plano_bomberil_solicitudes_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos',
            name='plano_bomberil',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
