# Generated by Django 5.1.2 on 2025-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_requisitos_plano_bomberil'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitos',
            name='documento_propiedad_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='referencia',
            field=models.CharField(default='NO HAY REFERENCIA'),
        ),
    ]
