# Generated by Django 5.1.2 on 2025-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_requisitos_documento_propiedad_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='rif_representante_legal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitante_cedula',
            field=models.CharField(blank=True, null=True),
        ),
    ]
