# Generated by Django 5.1.2 on 2025-02-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_alter_solicitudes_rif_representante_legal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='parroquia',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias'),
        ),
    ]
