# Generated by Django 5.1.2 on 2025-03-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_solicitudes_parroquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes_Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField()),
                ('fecha', models.DateField(default='1999-01-01')),
                ('hora', models.TimeField(default='00:00')),
                ('descripcion', models.CharField()),
                ('persona_responsable', models.CharField()),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades_Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField()),
                ('serial_carroceria', models.CharField()),
                ('serial_chasis', models.CharField()),
                ('marca', models.CharField()),
                ('año', models.CharField()),
                ('modelo', models.CharField()),
                ('placas', models.CharField()),
                ('tipo_filtro_aceite', models.CharField()),
                ('tipo_filtro_combustible', models.CharField()),
                ('bateria', models.CharField()),
                ('numero_tag', models.CharField()),
                ('tipo_bujia', models.CharField()),
                ('uso', models.CharField()),
                ('capacidad_carga', models.CharField()),
                ('numero_ejes', models.CharField()),
                ('numero_puestos', models.CharField()),
                ('tipo_combustible', models.CharField()),
                ('tipo_aceite', models.CharField()),
                ('medida_neumaticos', models.CharField()),
                ('tipo_correa', models.CharField()),
                ('estado', models.CharField()),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades')),
            ],
        ),
    ]
