# Generated by Django 5.1.2 on 2025-03-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_reportes_unidades_unidades_detalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='reportes_unidades',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.servicios'),
        ),
    ]
