# Generated by Django 5.1.2 on 2025-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_drones_registro_vuelos_estadodron_estadocontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesvuelo',
            name='viento',
            field=models.CharField(default=1979),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadodron',
            name='observacion_camara',
            field=models.CharField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='estadodron',
            name='observacion_cuerpo',
            field=models.CharField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='estadodron',
            name='observacion_helices',
            field=models.CharField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='estadodron',
            name='observacion_motores',
            field=models.CharField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='estadodron',
            name='observacion_sensores',
            field=models.CharField(default='Ninguna'),
        ),
    ]
