# Generated by Django 5.1.2 on 2025-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_detallesvuelo_viento_estadodron_observacion_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_vuelos',
            name='id_vuelo',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
