# Generated by Django 5.1.2 on 2025-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_registro_vuelos_id_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvuelo',
            name='altitud',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='distancia_recorrida',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='duracion_vuelo',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='numero_satelites',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='observaciones',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='riesgo_vuelo',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='detallesvuelo',
            name='zona_vuelo',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registro_vuelos',
            name='id_vuelo',
            field=models.CharField(default='', editable=False, unique=True),
        ),
    ]
