# Generated by Django 5.1.2 on 2025-04-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_alter_detallesvuelo_altitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BienMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('departamento', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('estado_actual', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=20)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('nuevo_estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=20)),
                ('reasignacion', models.CharField(blank=True, max_length=200, null=True)),
                ('ordenado_por', models.CharField(max_length=200)),
                ('fecha_orden', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='web.bienmunicipal')),
            ],
        ),
    ]
