# Generated by Django 5.1.2 on 2025-04-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_dependencia_bienmunicipal_movimientobien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienmunicipal',
            name='cantidad',
        ),
    ]
