# Generated by Django 5.1.2 on 2025-04-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_remove_bienmunicipal_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienmunicipal',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
    ]
