# Generated by Django 5.1.2 on 2025-04-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_alter_bienmunicipal_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientobien',
            name='fecha_movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientobien',
            name='nuevo_estado',
        ),
        migrations.RemoveField(
            model_name='movimientobien',
            name='reasignacion',
        ),
        migrations.AddField(
            model_name='bienmunicipal',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientobien',
            name='nueva_dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.dependencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientobien',
            name='nuevo_departamento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientobien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bienmunicipal'),
        ),
    ]
