# Generated by Django 5.1.2 on 2025-04-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_remove_movimientobien_fecha_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobien',
            name='ordenado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
    ]
