# Generated by Django 5.1.2 on 2025-04-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_alter_movimientobien_ordenado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiarEstadoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=20)),
                ('fecha_orden', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bienmunicipal')),
            ],
        ),
    ]
