# Generated by Django 5.1.2 on 2025-04-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_cambiarestadobien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='web.personal')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('centro_medico', models.CharField(max_length=200)),
                ('medico', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_medicos', to='web.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('A', 'Tipo A - Motocicletas'), ('B', 'Tipo B - Automóviles'), ('C', 'Tipo C - Camiones livianos'), ('D', 'Tipo D - Camiones pesados'), ('E', 'Tipo E - Maquinaria pesada'), ('F', 'Tipo F - Transporte público'), ('G', 'Tipo G - Vehículos especiales')], max_length=1)),
                ('numero_licencia', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('organismo_emisor', models.CharField(max_length=100)),
                ('restricciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='web.conductor')),
            ],
            options={
                'verbose_name': 'Licencia de Conductor',
                'verbose_name_plural': 'Licencias de Conductores',
                'unique_together': {('numero_licencia', 'tipo_licencia')},
            },
        ),
    ]
