# Generated by Django 5.1.2 on 2025-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_conductor_certificadomedico_licenciaconductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='cedula_identidad',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='licenciaconductor',
            name='tipo_licencia',
            field=models.CharField(choices=[('2', '2° Segundo Grado'), ('3', '3° Tercer Grado'), ('4', '4° Cuarto Grado'), ('5', '5° Quinto Grado')], max_length=1),
        ),
    ]
