# Generated by Django 5.1.2 on 2025-04-30 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_remove_conductor_cedula_identidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de herramientas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('P', 'En reparación')], max_length=1)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo'), ('P', 'En reparación')], default='B', max_length=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(auto_now_add=True)),
                ('realizado_por', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='licenciaconductor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='certificadomedico',
            constraint=models.UniqueConstraint(fields=('conductor',), name='unique_certificado_por_conductor'),
        ),
        migrations.AddConstraint(
            model_name='licenciaconductor',
            constraint=models.UniqueConstraint(fields=('numero_licencia', 'tipo_licencia'), name='unique_licencia_numero_tipo'),
        ),
        migrations.AddField(
            model_name='asignacionherramienta',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
        migrations.AddField(
            model_name='asignacionherramienta',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.categoriaherramienta'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.herramienta'),
        ),
        migrations.AddField(
            model_name='asignacionherramienta',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.herramienta'),
        ),
        migrations.AddField(
            model_name='inventariounidad',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.unidades'),
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inventariounidad'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionherramienta',
            unique_together={('herramienta', 'unidad', 'fecha_devolucion')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleinventario',
            unique_together={('inventario', 'herramienta')},
        ),
    ]
