# Generated by Django 5.1.2 on 2025-05-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_asignacionherramienta_categoriaherramienta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariounidad',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal'),
        ),
    ]
