# Generated by Django 5.1.2 on 2025-05-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0076_alter_inventariounidad_realizado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='requisitos',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='parroquia',
        ),
        migrations.DeleteModel(
            name='Comercio',
        ),
        migrations.DeleteModel(
            name='Requisitos',
        ),
        migrations.DeleteModel(
            name='Solicitudes',
        ),
    ]
