# Generated by Django 5.1.2 on 2025-06-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_remove_solicitudes_id_solicitud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionHerramienta',
        ),
        migrations.DeleteModel(
            name='CategoriaHerramienta',
        ),
        migrations.DeleteModel(
            name='CertificadoMedico',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='LicenciaConductor',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.DeleteModel(
            name='DetalleInventario',
        ),
        migrations.DeleteModel(
            name='InventarioUnidad',
        ),
        migrations.DeleteModel(
            name='Reportes_Unidades',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Unidades_Detalles',
        ),
    ]
