# Generated by Django 5.1.2 on 2025-07-01 19:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_remove_herramienta_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('actual', models.TextField()),
                ('jerarquia', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
