# Generated by Django 5.1.2 on 2025-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0079_ascensos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personal',
            name='direccion',
            field=models.TextField(default='Direccion no especificada'),
        ),
        migrations.AddField(
            model_name='detalles_personal',
            name='email',
            field=models.TextField(default='Email no especificado'),
        ),
        migrations.AddField(
            model_name='detalles_personal',
            name='horario',
            field=models.CharField(default='Horario no especificado'),
        ),
        migrations.AddField(
            model_name='detalles_personal',
            name='telefono',
            field=models.CharField(default='Telefono no especificado'),
        ),
    ]
