# Generated by Django 5.1.2 on 2025-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_detalles_personal_direccion_detalles_personal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_personal',
            name='horario',
            field=models.CharField(default='Horario no especificado'),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='telefono',
            field=models.CharField(default='Telefono no especificado'),
        ),
    ]
