# Generated by Django 5.1.2 on 2025-07-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_alter_detalles_personal_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_personal',
            name='horario',
            field=models.TextField(default='Horario no especificado'),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='telefono',
            field=models.TextField(default='Telefono no especificado'),
        ),
    ]
