# Generated by Django 5.1.2 on 2025-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0082_alter_detalles_personal_horario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ascensos',
            old_name='jerarquia',
            new_name='gaceta',
        ),
        migrations.AddField(
            model_name='ascensos',
            name='nuevo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
