# Generated by Django 5.1.2 on 2025-07-03 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_rename_jerarquia_ascensos_gaceta_ascensos_nuevo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('parentesco', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.TextField(blank=True, null=True)),
                ('partida_nacimiento', models.TextField(blank=True, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('sancion', models.TextField()),
                ('observaciones', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Titulos_Academicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('institucion', models.TextField()),
                ('fecha_obtencion', models.DateField(default=django.utils.timezone.now)),
                ('numero_constancia', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
