# Generated by Django 5.1.2 on 2025-07-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_familiares_sanciones_titulos_academicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulos_academicos',
            name='hrs_academicas',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
