# Generated by Django 5.1.2 on 2025-07-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0085_titulos_academicos_hrs_academicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personal',
            name='estado_civil',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='horario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='telefono',
            field=models.TextField(),
        ),
    ]
