# Generated by Django 5.1.2 on 2025-07-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0086_detalles_personal_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personal',
            name='banco',
            field=models.TextField(default='Banco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles_personal',
            name='nro_cuenta',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles_personal',
            name='seguro_social',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
