# Generated by Django 5.1.2 on 2025-07-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_detalles_personal_banco_detalles_personal_nro_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personal',
            name='nro_rif',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
