# Generated by Django 5.1.2 on 2025-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_detalles_personal_nro_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personal',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True),
        ),
    ]
