# Generated by Django 5.1.2 on 2025-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0089_detalles_personal_fecha_cese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientobien',
            name='bien',
        ),
        migrations.RemoveField(
            model_name='cambiarestadobien',
            name='bien',
        ),
        migrations.RemoveField(
            model_name='movimientobien',
            name='nueva_dependencia',
        ),
        migrations.RemoveField(
            model_name='detallesvuelo',
            name='id_vuelo',
        ),
        migrations.RemoveField(
            model_name='estadocontrol',
            name='id_dron',
        ),
        migrations.RemoveField(
            model_name='estadobaterias',
            name='id_dron',
        ),
        migrations.RemoveField(
            model_name='registro_vuelos',
            name='id_dron',
        ),
        migrations.RemoveField(
            model_name='estadodron',
            name='id_dron',
        ),
        migrations.RemoveField(
            model_name='estadobaterias',
            name='id_vuelo',
        ),
        migrations.RemoveField(
            model_name='estadocontrol',
            name='id_vuelo',
        ),
        migrations.RemoveField(
            model_name='estadodron',
            name='id_vuelo',
        ),
        migrations.RemoveField(
            model_name='movimientobien',
            name='ordenado_por',
        ),
        migrations.RemoveField(
            model_name='registro_vuelos',
            name='id_observador',
        ),
        migrations.RemoveField(
            model_name='registro_vuelos',
            name='id_operador',
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='banco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='estado_civil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='grupo_sanguineo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='horario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='nro_cuenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='nro_rif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='seguro_social',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='talla_camisa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='talla_pantalon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='talla_zapato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalles_personal',
            name='telefono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BienMunicipal',
        ),
        migrations.DeleteModel(
            name='CambiarEstadoBien',
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
        migrations.DeleteModel(
            name='DetallesVuelo',
        ),
        migrations.DeleteModel(
            name='Drones',
        ),
        migrations.DeleteModel(
            name='EstadoBaterias',
        ),
        migrations.DeleteModel(
            name='EstadoControl',
        ),
        migrations.DeleteModel(
            name='EstadoDron',
        ),
        migrations.DeleteModel(
            name='MovimientoBien',
        ),
        migrations.DeleteModel(
            name='Registro_Vuelos',
        ),
    ]
