# Generated by Django 5.1.2 on 2025-07-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0090_remove_movimientobien_bien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones_Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.TextField()),
                ('fecha_desde', models.TextField()),
                ('cantidad_dias', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
