# Generated by Django 5.1.2 on 2025-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_vacaciones_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones_permisos',
            name='tipo',
            field=models.TextField(default='Permisos'),
            preserve_default=False,
        ),
    ]
