# Generated by Django 5.1.2 on 2025-07-30 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0092_vacaciones_permisos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
