# Generated by Django 5.1.2 on 2025-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0093_usuarios_last_activity_usuarios_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='online',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
