# Generated by Django 5.1.2 on 2025-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0094_remove_usuarios_last_activity_remove_usuarios_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
