# Generated by Django 5.1.2 on 2025-08-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0095_alter_detalles_personal_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Titulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_titulo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='titulos_academicos',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipos_titulaciones'),
        ),
    ]
