# Generated by Django 5.1.2 on 2025-07-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0090_remove_movimientobien_bien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BienMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(default='none')),
                ('cantidad', models.IntegerField(default=0)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('estado_actual', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=20)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_municipales.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='CambiarEstadoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Defectuoso', 'Defectuoso'), ('Dañado', 'Dañado')], max_length=20)),
                ('fecha_orden', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_municipales.bienmunicipal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_departamento', models.CharField(default='none', max_length=20)),
                ('fecha_orden', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_municipales.bienmunicipal')),
                ('nueva_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_municipales.dependencia')),
                ('ordenado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.personal')),
            ],
        ),
    ]
