"""
Django settings for Web_App project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# esto lo estoy probando
# BASE_DIR = Path(__file__).resolve().parent.parent /esta es la original
# esto es para el render
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-usf!gyb)c_93(yhk-ab2gm%&_(hlk1ough81m110qhhrn4$cvy'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug true significa desarrollo modo de pruebas
DEBUG = True

#------------- modo produccion-----------------
# Debug false significa produccion quiere decir listo para usarse
# DEBUG = False

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['localhost', '127.0.0.1','cuerpobomberossc.com', 'www.cuerpobomberossc.com','bomberos-production.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "web",
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'web.middleware.LogoutIfAuthenticatedMiddleware',  # Tu middleware existente
    'web.middleware.NoCacheMiddleware',  # Ajusta esto según tu estructura
    'web.middleware.LoadingScreenMiddleware',
    'web.middleware.RegistroPeticionesMiddleware',
]

LOGIN_URL = 'home'  # Cambia esto al nombre de tu URL de inicio de sesión
LOGIN_REDIRECT_URL = '/dashboard/'  # Cambia esto a la vista a la que quieres redirigir después del inicio de sesión

SESSION_COOKIE_AGE = 18000  # Tiempo en segundos (15 minutos)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Cierra sesión al cerrar el navegador

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'Web_App.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Web_App.wsgi.application'

# app PWA

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  'web/static'),
]

PWA_APP_NAME = 'Cuerpo Bomberos SC'
PWA_APP_DESCRIPTION = "App Web del cuerpo de bomberos"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/logo bomberos 2.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'web/static/js/pwa/serviceworker.js')




# ------------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME': BASE_DIR / 'db.sqlite3', comentada para el render esta es original
#         # nueva linea para el render 
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'bomberos_db',
#         'USER': 'postgres',
#         'PASSWORD': 'anthonym7',
#         'PORT': '5432',
#         'HOST': 'localhost'
#     }
# }

# Base de Datos del Render (Sala Situacional)
# DATABASES = {
#     'default': dj_database_url.config(default="postgresql://bomberos_db_user:5wuTseoCTH2EvZaKsR7Ct529uc8sdpVg@dpg-csp2esm8ii6s73a525sg-a.oregon-postgres.render.com/bomberos_db")
# }

# Conexion base de datos del Render (Sala Situacional) 2
DATABASES = {
    'default': dj_database_url.config(default="postgresql://bomberos_dbs_user:sB0cG00nvzS11aSYoROt2wNSWPnSIDyR@dpg-ctct69btq21c7380aogg-a.oregon-postgres.render.com/bomberos_dbs")
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_I18N = True

SESSION_COOKIE_SECURE = False  # Usar cookies seguras solo en HTTPS
CSRF_COOKIE_SECURE = False  # Usar cookies seguras para CSRF

USE_TZ = True
TIME_ZONE = 'America/Caracas'  # Usa la zona horaria de tu región


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
