# Generated by Django 5.1.2 on 2025-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven911', '0001_initial'),
    ]

    operations = [
    ]
