# Generated by Django 5.1.2 on 2025-05-31 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven911', '0002_remove_servicio_descripcion_and_more'),
        ('web', '0077_remove_solicitudes_id_solicitud_and_more'),
    ]

    operations = [
    ]
