# Generated by Django 5.1.2 on 2025-06-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven911', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tipo_servicio', models.IntegerField(default=1)),
                ('fecha', models.DateField(default='1999-02-02')),
                ('hora', models.TimeField(default='00:00')),
                ('operador_de_guardia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_como_operador', to='web.personal')),
                ('tipo_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ven911.tiposervicio')),
            ],
        ),
    ]
