# Generated by Django 5.1.2 on 2025-05-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0077_remove_solicitudes_id_solicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comercio', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('nombre_comercio', models.CharField(max_length=100)),
                ('rif_empresarial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('hora_solicitud', models.TimeField()),
                ('tipo_servicio', models.CharField()),
                ('solicitante_nombre_apellido', models.CharField()),
                ('solicitante_cedula', models.CharField(blank=True, null=True)),
                ('tipo_representante', models.CharField()),
                ('rif_representante_legal', models.CharField(blank=True, null=True)),
                ('direccion', models.CharField()),
                ('estado', models.CharField()),
                ('numero_telefono', models.CharField()),
                ('correo_electronico', models.CharField()),
                ('pago_tasa', models.CharField()),
                ('metodo_pago', models.CharField()),
                ('referencia', models.CharField(default='NO HAY REFERENCIA')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad_prevencion.comercio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.municipios')),
                ('parroquia', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='web.parroquias')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.BooleanField(default=False)),
                ('cedula_vencimiento', models.DateField(blank=True, null=True)),
                ('rif_representante', models.BooleanField(default=False)),
                ('rif_representante_vencimiento', models.DateField(blank=True, null=True)),
                ('rif_comercio', models.BooleanField(default=False)),
                ('rif_comercio_vencimiento', models.DateField(blank=True, null=True)),
                ('permiso_anterior', models.BooleanField(default=False)),
                ('registro_comercio', models.BooleanField(default=False)),
                ('documento_propiedad', models.BooleanField(default=False)),
                ('documento_propiedad_vencimiento', models.DateField(blank=True, null=True)),
                ('cedula_catastral', models.BooleanField(default=False)),
                ('cedula_catastral_vencimiento', models.DateField(blank=True, null=True)),
                ('carta_autorizacion', models.BooleanField(default=False)),
                ('plano_bomberil', models.BooleanField(blank=True, default=False)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad_prevencion.solicitudes')),
            ],
        ),
    ]
