# Generated by Django 5.1.2 on 2025-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_prevencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='departamento',
            field=models.CharField(default='San Cristobal', max_length=100),
            preserve_default=False,
        ),
    ]
