# Generated by Django 5.1.2 on 2025-05-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_prevencion', '0002_comercio_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='referencia',
            field=models.CharField(default='No Hay Referencia'),
        ),
    ]
