# Generated by Django 5.1.2 on 2025-07-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_prevencion', '0003_alter_solicitudes_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='referencia',
            field=models.CharField(blank=True, default='No Hay Referencia', null=True),
        ),
    ]
