# Generated by Django 5.1.2 on 2025-07-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dron', models.CharField(max_length=100)),
                ('id_dron', models.CharField(max_length=50, unique=True)),
                ('modelo_dron', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vuelo', models.CharField(default='', editable=False, unique=True)),
                ('observador_externo', models.TextField(blank=True, default='Interno')),
                ('fecha', models.DateField(default='1999-01-01')),
                ('sitio', models.CharField()),
                ('hora_despegue', models.TimeField(default='00:00')),
                ('hora_aterrizaje', models.TimeField(default='00:00')),
                ('tipo_mision', models.CharField(max_length=100)),
                ('observaciones_vuelo', models.CharField()),
                ('apoyo_realizado_a', models.CharField()),
                ('id_dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.drones')),
                ('id_observador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observador', to='web.personal')),
                ('id_operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador', to='web.personal')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=5)),
                ('observacion_cuerpo', models.CharField(default='Ninguna')),
                ('camara', models.CharField(max_length=5)),
                ('observacion_camara', models.CharField(default='Ninguna')),
                ('helices', models.CharField(max_length=5)),
                ('observacion_helices', models.CharField(default='Ninguna')),
                ('sensores', models.CharField(max_length=5)),
                ('observacion_sensores', models.CharField(default='Ninguna')),
                ('motores', models.CharField(max_length=5)),
                ('observacion_motores', models.CharField(default='Ninguna')),
                ('id_dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.drones')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.registro_vuelos')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=5)),
                ('joysticks', models.CharField(max_length=5)),
                ('pantalla', models.CharField(max_length=5)),
                ('antenas', models.CharField(max_length=5)),
                ('bateria', models.CharField(max_length=5)),
                ('id_dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.drones')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.registro_vuelos')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria1', models.CharField(max_length=5)),
                ('bateria2', models.CharField(max_length=5)),
                ('bateria3', models.CharField(max_length=5)),
                ('bateria4', models.CharField(max_length=5)),
                ('id_dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.drones')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.registro_vuelos')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viento', models.CharField()),
                ('nubosidad', models.CharField()),
                ('riesgo_vuelo', models.CharField()),
                ('zona_vuelo', models.CharField()),
                ('numero_satelites', models.CharField()),
                ('distancia_recorrida', models.CharField()),
                ('altitud', models.CharField()),
                ('duracion_vuelo', models.CharField()),
                ('observaciones', models.CharField()),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarp.registro_vuelos')),
            ],
        ),
    ]
